### ISSUE TITLE
Add update interval

### ISSUE THREAD

**Issue by vlumikero** [tubalainen/sparsnas_decoder#24]
I managed to fry my SD card when I set up the decoder a while back so my idea was that it would be nice if the update frequency could be set it the config to reduce the load on the storage medium.

**Comment by fredrike** [comment]
The update frequency is not something that can be configured. The decoder reacts on data from the sender.

**Comment by vlumikero** [comment]
Do you know if it’s possible to change somewhere on it’s way to hass?

**Comment by fredrike** [comment]
> Do you know if it’s possible to change somewhere on it’s way to hass?

No not really, you could however stop HA to write stuff to the memory card..
