### ISSUE TITLE
expected a dictionary for dictionary value @ data['packages']['sensor']

### ISSUE THREAD

**Issue by a94marbo** [tubalainen/sparsnas_decoder#26]
I get this error in HA configuration check:
"expected a dictionary for dictionary value @ data['packages']['sensor']"

I have all other pre-reqs installed. 
- custom_ui
- incoming mgtt packets according to documentation
- sparsnas_mqtt.yaml in packages folder, and correct setup in configuration.yaml

Running  core-2021.1.4, supervisor-2021.01.5

**Comment by fredrike** [comment]
Do you really have this in configuration.yaml

```yaml
homeassistant:
  packages: !include_dir_named packages
```

**Comment by a94marbo** [comment]
works
