### ISSUE TITLE
mqtt client do not send topics anymore

### ISSUE THREAD

**Issue by a94marbo** [tubalainen/sparsnas_decoder#28]
Recently the mqtt messaging stopped working. The client logs in to home assistant, but not topics are being published to home assistant. I cannot detect any topics being sent from the sparnär client to home asssiant. New breaking update on lmosquitto?

Updated: 
- mosquitto_pub from prompt works to publish to hass.io broker.
- sparsnas_decode works for fetching values. Values are correct.
I cannot verify if mosq struct is built correctly.
Any way of hardcoding host, port, user name and password in mosquitto_publish?

**Comment by roflcoopter** [comment]
@a94marbo  Did you solve this? Got the same issues

**Comment by a94marbo** [comment]
Nope, never got it to work again.
I moved to the internal HASS integration of sparsnas instead.

**Comment by tubalainen** [comment]
I am sorry, this repository will not be maintained. Please use alternative solutions to grab the Sparsnäs signal.
